version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps)"
    open-pull-requests-limit: 10
    groups:
      angular:
        patterns:
          - "@angular/*"
          - "@angular-devkit/*"
          - "@schematics/angular"
      eslint:
        patterns:
          - "*eslint*"
          - "typescript-eslint"
      dev-tools:
        patterns:
          - "prettier*"
          - "husky"
          - "vitest*"
          - "jsdom"
          - "typescript"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(ci)"
    open-pull-requests-limit: 5
