allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
minimumReleaseAgeExclude:
  - '@angular-devkit/architect@0.2201.3'
  - '@angular-devkit/core@22.1.3'
  - '@angular-devkit/schematics@22.1.3'
  - '@angular/build@22.1.3'
  - '@angular/cdk@22.1.1'
  - '@angular/cli@22.1.3'
  - '@schematics/angular@22.1.3'
  - '@types/node@26.4.1'
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - lmdb
  - msgpackr-extract
overrides:
  '@typescript-eslint/utils': ^8.69.0
  '@typescript-eslint/typescript-estree': ^8.69.0
  '@typescript-eslint/types': ^8.69.0
  '@typescript-eslint/project-service': ^8.69.0
  '@typescript-eslint/tsconfig-utils': ^8.69.0
  '@typescript-eslint/parser': ^8.69.0
  '@typescript-eslint/eslint-plugin': ^8.69.0
